### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by shadowfox87** [sporkwitch/tournamentbot#2]
There's not any Discord bots on the net that use the challonge API. If possible, please continue this project. It is needed in the community. The TournyBot should be able to start a tournament, add a participant, send a pm to participant in Discord of who their next opponent is, publish bracket results.

If you want to go one step further, calculate Trueskill ratings. There is code here that does this here: https://github.com/SugoiFactory/SkillKeeper

**Comment by sporkwitch** [comment]
Sorry for the long delay in response.  Yes, it's basically abandoned, as I don't really have the time or inclination to work on it.  I encourage anyone interested in maintaining it to fork and use it as they wish (keeping the licesning and the wishes of the musicbot creator in mind).  If I see any pull requests I'll certainly look them over, and if someone is interested I'm not averse to adding someone as a maintainer.

**Comment by jamalcwoods** [comment]
I have started working on a Discord bot that uses the challonge API, it's capabilities are limited but it is able to do a few basic functions like create and run through a tournament all from discord
