### ISSUE TITLE
help???

### ISSUE THREAD

**Issue by BentleyManiac** [sporkwitch/tournamentbot#3]
I'm trying to set up the bot on a raspberry pi, and I keep getting this error:
`root@raspberrypi:/srv/dev-disk-by-label-Settings/discordbot/tournamentbot# sudo python3.5 run.py
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main()
  File "run.py", line 182, in main
    AutoLoginBot().run()
  File "/srv/dev-disk-by-label-Settings/discordbot/tournamentbot/autologin/bot.py", line 351, in __init__
    self.voice_clients = {}
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 300, in __setattr__
    return setattr(self.connection, name, value)
AttributeError: can't set attribute
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x769bc970>
`
any idea what the problem is?
is it possibly a file permissions problem, or have I configured it wrong?

**Comment by sporkwitch** [comment]
My first assumptions would be either A) missing deps, or B) You haven't correctly updated it to use the bot API.  As noted in the description, this is from before the bot API was required, and I no longer maintain the project.  You are welcome to fork it and patch it accordingly.
